#!/usr/bin/env node

/**
 * Strudel MCP Server
 *
 * MCP server for natural language control of Strudel live coding
 * from Claude Code.
 *
 * @author Gonzalo Riederer
 * @license MIT
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

// Import tool implementations
import { createPattern } from './tools/create.js';
import { modifyPattern, getCurrentPattern } from './tools/modify.js';
import { stop, start, setTempo, getCurrent } from './tools/control.js';
import { savePattern, loadPattern, listPatterns } from './tools/persistence.js';

/**
 * MCP Server instance
 */
const server = new Server(
  {
    name: 'strudel-mcp',
    version: '0.1.0',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

/**
 * Tool Definitions
 *
 * These are the MCP tools exposed to Claude Code
 */
const tools = [
  {
    name: 'strudel_create',
    description:
      'Create a new Strudel pattern from natural language description. Claude should generate the Strudel code and pass it as the "code" parameter.',
    inputSchema: {
      type: 'object',
      properties: {
        description: {
          type: 'string',
          description: 'Natural language description of the musical pattern',
        },
        code: {
          type: 'string',
          description: 'Generated Strudel pattern code (generated by Claude)',
        },
      },
      required: ['description', 'code'],
    },
  },
  {
    name: 'strudel_modify',
    description:
      'Modify the current active Strudel pattern. Claude should generate the modified Strudel code and pass it as the "code" parameter.',
    inputSchema: {
      type: 'object',
      properties: {
        modification: {
          type: 'string',
          description: 'Natural language description of the modification',
        },
        code: {
          type: 'string',
          description: 'Modified Strudel pattern code (generated by Claude)',
        },
      },
      required: ['modification', 'code'],
    },
  },
  {
    name: 'strudel_set_tempo',
    description: 'Set the global tempo in BPM',
    inputSchema: {
      type: 'object',
      properties: {
        bpm: {
          type: 'number',
          description: 'Tempo in beats per minute',
        },
      },
      required: ['bpm'],
    },
  },
  {
    name: 'strudel_stop',
    description: 'Stop audio playback',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'strudel_start',
    description: 'Resume audio playback',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'strudel_save_pattern',
    description: 'Save the current pattern to a file',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Name for the pattern file (without extension)',
        },
        description: {
          type: 'string',
          description: 'Optional description of the pattern',
        },
        tags: {
          type: 'array',
          items: { type: 'string' },
          description: 'Optional tags for the pattern',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'strudel_load_pattern',
    description: 'Load a saved pattern from file and start playing it',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Name of the pattern to load',
        },
      },
      required: ['name'],
    },
  },
  {
    name: 'strudel_list_patterns',
    description: 'List all saved patterns',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'strudel_get_current',
    description: 'Get the current pattern state (code, BPM, playing status)',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
];

/**
 * Handler: List Tools
 */
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools,
  };
});

/**
 * Handler: Call Tool
 */
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    let result;

    switch (name) {
      case 'strudel_create':
        result = await createPattern(args.code);
        return {
          content: [
            {
              type: 'text',
              text: `🎵 Pattern created and playing!\n\nCode:\n\`\`\`javascript\n${result.code}\n\`\`\`\n\nThe pattern is now playing in the browser.`,
            },
          ],
        };

      case 'strudel_modify':
        result = await modifyPattern(args.code);
        return {
          content: [
            {
              type: 'text',
              text: `🎵 Pattern modified!\n\nNew code:\n\`\`\`javascript\n${result.code}\n\`\`\`\n\nThe updated pattern is now playing.`,
            },
          ],
        };

      case 'strudel_set_tempo':
        result = await setTempo(args.bpm);
        return {
          content: [
            {
              type: 'text',
              text: `🎵 Tempo set to ${result.bpm} BPM (${result.cps.toFixed(3)} cycles/second)`,
            },
          ],
        };

      case 'strudel_stop':
        result = await stop();
        return {
          content: [
            {
              type: 'text',
              text: '⏸️ Playback stopped.',
            },
          ],
        };

      case 'strudel_start':
        result = await start();
        return {
          content: [
            {
              type: 'text',
              text: '▶️ Playback started.',
            },
          ],
        };

      case 'strudel_save_pattern':
        result = await savePattern(args.name, args.description || '', args.tags || []);
        return {
          content: [
            {
              type: 'text',
              text: `💾 Pattern saved as "${args.name}"\n\nLocation: ${result.filepath}`,
            },
          ],
        };

      case 'strudel_load_pattern':
        result = await loadPattern(args.name);
        return {
          content: [
            {
              type: 'text',
              text: `📂 Pattern "${result.name}" loaded!\n\nCode:\n\`\`\`javascript\n${result.code}\n\`\`\`\n\nBPM: ${result.bpm}\n${result.description ? `Description: ${result.description}\n` : ''}The pattern is now playing.`,
            },
          ],
        };

      case 'strudel_list_patterns':
        result = await listPatterns();
        if (result.count === 0) {
          return {
            content: [
              {
                type: 'text',
                text: '📁 No saved patterns found.\n\nCreate and save patterns to see them here!',
              },
            ],
          };
        }

        const patternList = result.patterns
          .map(
            (p, i) =>
              `${i + 1}. **${p.name}**\n   - BPM: ${p.bpm}\n   - Modified: ${new Date(p.modified).toLocaleString()}${p.description ? `\n   - ${p.description}` : ''}`
          )
          .join('\n\n');

        return {
          content: [
            {
              type: 'text',
              text: `📁 Saved Patterns (${result.count})\n\n${patternList}`,
            },
          ],
        };

      case 'strudel_get_current':
        result = await getCurrent();
        if (!result.code) {
          return {
            content: [
              {
                type: 'text',
                text: '🎵 No active pattern.\n\nCreate a pattern to get started!',
              },
            ],
          };
        }

        return {
          content: [
            {
              type: 'text',
              text: `🎵 Current Pattern\n\nCode:\n\`\`\`javascript\n${result.code}\n\`\`\`\n\nBPM: ${result.bpm}\nPlaying: ${result.playing ? 'Yes ▶️' : 'No ⏸️'}\nLast modified: ${result.lastModified ? new Date(result.lastModified).toLocaleString() : 'N/A'}`,
            },
          ],
        };

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (error) {
    return {
      content: [
        {
          type: 'text',
          text: `❌ Error: ${error.message}\n\nPlease try again or check the logs for details.`,
        },
      ],
      isError: true,
    };
  }
});

/**
 * Start Server
 */
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('Strudel MCP server running on stdio');
  console.error('Ready to create music! 🎵');
}

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
