/**
 * Create Pattern Tool
 *
 * Creates new Strudel patterns from natural language
 */

import { executePattern } from '../strudel.js';
import { setCode, setPlaying } from '../state.js';
import { debug } from '../utils.js';

/**
 * Create pattern from natural language description
 *
 * Note: The actual natural language ’ code conversion is done by Claude.
 * This function receives the generated code and executes it.
 *
 * @param {string} code - Strudel code (generated by Claude)
 * @returns {Promise<Object>} Result
 */
export async function createPattern(code) {
  try {
    debug('Creating pattern', { code });

    // Execute the pattern
    const result = await executePattern(code);

    // Update state
    setCode(code);
    setPlaying(true);

    return {
      success: true,
      code,
      playing: true,
      message: `Pattern created and playing: ${code}`,
    };
  } catch (error) {
    debug('Create pattern failed', { error: error.message });
    throw error;
  }
}
