/**
 * Modify Pattern Tool
 *
 * Modifies existing Strudel patterns
 */

import { executePattern } from '../strudel.js';
import { getCurrentCode, setCode, setPlaying } from '../state.js';
import { debug } from '../utils.js';

/**
 * Modify current pattern
 *
 * Note: The actual modification logic is handled by Claude.
 * This function receives the modified code and executes it.
 *
 * @param {string} newCode - Modified Strudel code (generated by Claude)
 * @returns {Promise<Object>} Result
 */
export async function modifyPattern(newCode) {
  try {
    const currentCode = getCurrentCode();

    if (!currentCode) {
      throw new Error('No active pattern to modify');
    }

    debug('Modifying pattern', { from: currentCode, to: newCode });

    // Execute the modified pattern
    const result = await executePattern(newCode);

    // Update state
    setCode(newCode);
    setPlaying(true);

    return {
      success: true,
      code: newCode,
      playing: true,
      message: `Pattern modified: ${newCode}`,
    };
  } catch (error) {
    debug('Modify pattern failed', { error: error.message });
    throw error;
  }
}

/**
 * Get current pattern code
 *
 * @returns {Promise<Object>} Current pattern info
 */
export async function getCurrentPattern() {
  const code = getCurrentCode();

  return {
    success: true,
    code,
    hasPattern: code.length > 0,
  };
}
